spring.application.name=budgeting

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.8
spring.ai.openai.chat.options.response-format.type=TEXT

spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=TEXT
spring.ai.openai.audio.transcription.options.prompt=Áudio em português brasileiro. Áudio contem descrição de gastos financeiros. \
  Contem um valor em reais (R$ 30,00 por exemplo); \
  Uma ação (gastei, paguei, etc.); \
  Um local ou estabelecimento (mercado, cinema, praça, farmácia, etc.)

spring.ai.model.audio.transcription=openai

logging.level.org.springframework.ai=DEBUG